package com.scrape.BO;
// Generated May 17, 2015 3:47:49 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MobileConfiguration generated by hbm2java
 */
@Entity
@Table(name="MOBILE_CONFIGURATION"
    ,schema="dbo"
    , uniqueConstraints = @UniqueConstraint(columnNames="MOBILE_DATA_ID") 
)
public class MobileConfiguration{


     private long id;
     private long mobileDataId;
     private String itemCode;
     private String partno;
     private String model;
     private String screenText;
     private String cpuText;
     private String ramText;
     private String osText;
     private String BCameraText;
     private String FCameraText;
     private String storageText;
     private String batteryText;
     private String simText;
     private String screen;
     private String cpu;
     private String ram;
     private String os;
     private String BCamera;
     private String FCamera;
     private String storage;
     private String battery;
     private String sim;
     private String color;
     private Date createDate;
     private Date lastUpdate;
     private String speed;
     private String approve;

    public MobileConfiguration() {
    }

	
    public MobileConfiguration(long id, long mobileDataId) {
        this.id = id;
        this.mobileDataId = mobileDataId;
    }
    public MobileConfiguration(long id, long mobileDataId, String itemCode, String partno, String model, String screenText, String cpuText, String ramText, String osText, String BCameraText, String FCameraText, String storageText, String batteryText, String simText, String screen, String cpu, String ram, String os, String BCamera, String FCamera, String storage, String battery, String sim, String color, Date createDate, Date lastUpdate, String speed) {
       this.id = id;
       this.mobileDataId = mobileDataId;
       this.itemCode = itemCode;
       this.partno = partno;
       this.model = model;
       this.screenText = screenText;
       this.cpuText = cpuText;
       this.ramText = ramText;
       this.osText = osText;
       this.BCameraText = BCameraText;
       this.FCameraText = FCameraText;
       this.storageText = storageText;
       this.batteryText = batteryText;
       this.simText = simText;
       this.screen = screen;
       this.cpu = cpu;
       this.ram = ram;
       this.os = os;
       this.BCamera = BCamera;
       this.FCamera = FCamera;
       this.storage = storage;
       this.battery = battery;
       this.sim = sim;
       this.color = color;
       this.createDate = createDate;
       this.lastUpdate = lastUpdate;
       this.speed = speed;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false, precision=18, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="MOBILE_DATA_ID", unique=true, nullable=false, precision=18, scale=0)
    public long getMobileDataId() {
        return this.mobileDataId;
    }
    
    public void setMobileDataId(long mobileDataId) {
        this.mobileDataId = mobileDataId;
    }
    
    @Column(name="ITEM_CODE", length=50)
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }
    
    @Column(name="PARTNO", length=50)
    public String getPartno() {
        return this.partno;
    }
    
    public void setPartno(String partno) {
        this.partno = partno;
    }
    
    @Column(name="MODEL", length=150)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    
    @Column(name="SCREEN_TEXT", length=250)
    public String getScreenText() {
        return this.screenText;
    }
    
    public void setScreenText(String screenText) {
        this.screenText = screenText;
    }
    
    @Column(name="CPU_TEXT", length=250)
    public String getCpuText() {
        return this.cpuText;
    }
    
    public void setCpuText(String cpuText) {
        this.cpuText = cpuText;
    }
    
    @Column(name="RAM_TEXT", length=250)
    public String getRamText() {
        return this.ramText;
    }
    
    public void setRamText(String ramText) {
        this.ramText = ramText;
    }
    
    @Column(name="OS_TEXT", length=250)
    public String getOsText() {
        return this.osText;
    }
    
    public void setOsText(String osText) {
        this.osText = osText;
    }
    
    @Column(name="B_CAMERA_TEXT", length=250)
    public String getBCameraText() {
        return this.BCameraText;
    }
    
    public void setBCameraText(String BCameraText) {
        this.BCameraText = BCameraText;
    }
    
    @Column(name="F_CAMERA_TEXT", length=250)
    public String getFCameraText() {
        return this.FCameraText;
    }
    
    public void setFCameraText(String FCameraText) {
        this.FCameraText = FCameraText;
    }
    
    @Column(name="STORAGE_TEXT", length=250)
    public String getStorageText() {
        return this.storageText;
    }
    
    public void setStorageText(String storageText) {
        this.storageText = storageText;
    }
    
    @Column(name="BATTERY_TEXT", length=250)
    public String getBatteryText() {
        return this.batteryText;
    }
    
    public void setBatteryText(String batteryText) {
        this.batteryText = batteryText;
    }
    
    @Column(name="SIM_TEXT", length=250)
    public String getSimText() {
        return this.simText;
    }
    
    public void setSimText(String simText) {
        this.simText = simText;
    }
    
    @Column(name="SCREEN", length=50)
    public String getScreen() {
        return this.screen;
    }
    
    public void setScreen(String screen) {
        this.screen = screen;
    }
    
    @Column(name="CPU", length=50)
    public String getCpu() {
        return this.cpu;
    }
    
    public void setCpu(String cpu) {
        this.cpu = cpu;
    }
    
    @Column(name="RAM", length=50)
    public String getRam() {
        return this.ram;
    }
    
    public void setRam(String ram) {
        this.ram = ram;
    }
    
    @Column(name="OS", length=50)
    public String getOs() {
        return this.os;
    }
    
    public void setOs(String os) {
        this.os = os;
    }
    
    @Column(name="B_CAMERA", length=50)
    public String getBCamera() {
        return this.BCamera;
    }
    
    public void setBCamera(String BCamera) {
        this.BCamera = BCamera;
    }
    
    @Column(name="F_CAMERA", length=50)
    public String getFCamera() {
        return this.FCamera;
    }
    
    public void setFCamera(String FCamera) {
        this.FCamera = FCamera;
    }
    
    @Column(name="STORAGE", length=50)
    public String getStorage() {
        return this.storage;
    }
    
    public void setStorage(String storage) {
        this.storage = storage;
    }
    
    @Column(name="BATTERY", length=50)
    public String getBattery() {
        return this.battery;
    }
    
    public void setBattery(String battery) {
        this.battery = battery;
    }
    
    @Column(name="SIM", length=50)
    public String getSim() {
        return this.sim;
    }
    
    public void setSim(String sim) {
        this.sim = sim;
    }
    
    @Column(name="COLOR", length=50)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=23)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATE", length=23)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    
    @Column(name="SPEED", length=50)
    public String getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(String speed) {
        this.speed = speed;
    }

    @Column(name="APPROVE", length=1)
    public String getApprove() {
        return this.approve;
    }

    public void setApprove(String approve) {
        this.approve = approve;
    }

}


