package com.scrape.BO;
// Generated Aug 28, 2015 1:41:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pattern generated by hbm2java
 */
@Entity
@Table(name="PATTERN"
    ,schema="dbo"
)
public class Pattern{


     private long id;
     private String type;
     private String value;
     private String pattern;
     private Integer priority;
     private Character isactive;
     private Date createDate;
     private Date lastUpdate;
     private String category;
     private String useFor;
     private String pbegin;
     private String notContains;
     private String pbetween;
     private String price;

    public Pattern() {
    }

	
    public Pattern(long id) {
        this.id = id;
    }

    public Pattern(long id, String type, String value, String pattern, Integer priority, Character isactive, Date createDate, Date lastUpdate, String category, String useFor, String pbegin, String notContains, String pbetween, String price) {
        this.id = id;
        this.type = type;
        this.value = value;
        this.pattern = pattern;
        this.priority = priority;
        this.isactive = isactive;
        this.createDate = createDate;
        this.lastUpdate = lastUpdate;
        this.category = category;
        this.useFor = useFor;
        this.pbegin = pbegin;
        this.notContains = notContains;
        this.pbetween = pbetween;
        this.price = price;
    }


   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="TYPE", length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="VALUE", length=50)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="PATTERN", length=500)
    public String getPattern() {
        return this.pattern;
    }
    
    public void setPattern(String pattern) {
        this.pattern = pattern;
    }
    
    @Column(name="PRIORITY")
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    
    @Column(name="ISACTIVE", length=1)
    public Character getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }
    
    @Column(name="CREATE_DATE", length=10)
    @Temporal(TemporalType.DATE)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    @Column(name="LAST_UPDATE", length=10)
    @Temporal(TemporalType.DATE)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    
    @Column(name="CATEGORY", length=50)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    
    @Column(name="USE_FOR", length=50)
    public String getUseFor() {
        return this.useFor;
    }
    
    public void setUseFor(String useFor) {
        this.useFor = useFor;
    }
    
    @Column(name="pBEGIN", length=50)
    public String getPbegin() {
        return pbegin;
    }

    public void setPbegin(String pbegin) {
        this.pbegin = pbegin;
    }

    @Column(name="NOT_CONTAINS", length=500)
    public String getNotContains() {
        return this.notContains;
    }
    
    public void setNotContains(String notContains) {
        this.notContains = notContains;
    }
    
    @Column(name="pBETWEEN", length=50)
    public String getPbetween() {
        return pbetween;
    }

    public void setPbetween(String pbetween) {
        this.pbetween = pbetween;
    }
    
    @Column(name="PRICE", length=50)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }




}


