package com.scrape.BO;
// Generated Sep 22, 2015 2:04:27 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RoleMenu generated by hbm2java
 */
@Entity
@Table(name="ROLE_MENU"
    ,schema="dbo"
    , uniqueConstraints = @UniqueConstraint(columnNames={"MENU_ID", "ROLE_ID"}) 
)
public class RoleMenu{


     private long id;
     private Long roleId;
     private Long menuId;
     private String isactive;

    public RoleMenu() {
    }

	
    public RoleMenu(long id) {
        this.id = id;
    }
    public RoleMenu(long id, Long roleId, Long menuId, String isactive) {
       this.id = id;
       this.roleId = roleId;
       this.menuId = menuId;
       this.isactive = isactive;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="ROLE_ID", precision=10, scale=0)
    public Long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
    
    @Column(name="MENU_ID", precision=10, scale=0)
    public Long getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }
    
    @Column(name="ISACTIVE", length=1)
    public String getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }




}


