package com.scrape.BO;
// Generated Sep 3, 2015 2:54:40 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="ROLES"
    ,schema="dbo"
)
public class Roles{


     private long id;
     private String value;
     private String name;
     private String description;
     private String isactive;
     private String lastUpdate;
     private String createDate;

    public Roles() {
    }

	
    public Roles(long id, String value, String name) {
        this.id = id;
        this.value = value;
        this.name = name;
    }
    public Roles(long id, String value, String name, String description, String isactive, String lastUpdate, String createDate) {
       this.id = id;
       this.value = value;
       this.name = name;
       this.description = description;
       this.isactive = isactive;
       this.lastUpdate = lastUpdate;
       this.createDate = createDate;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="VALUE", nullable=false, length=50)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="ISACTIVE", length=1)
    public String getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }
    
    @Column(name="LAST_UPDATE", length=10)
    public String getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(String lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    
    @Column(name="CREATE_DATE", length=10)
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

}


