package com.scrape.BO;
// Generated Sep 3, 2015 2:54:40 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name="USER_ROLE"
    ,schema="dbo"
    , uniqueConstraints = @UniqueConstraint(columnNames={"USER_ID", "ROLE_ID"})
)
public class UserRole{


     private long id;
     private Long userId;
     private Long roleId;
     private String isactive;

    public UserRole() {
    }

	
    public UserRole(long id) {
        this.id = id;
    }
    public UserRole(long id, Long userId, Long roleId) {
       this.id = id;
       this.userId = userId;
       this.roleId = roleId;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="USER_ID", precision=10, scale=0)
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    @Column(name="ROLE_ID", precision=10, scale=0)
    public Long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Column(name="ISACTIVE", length=1)
    public String getIsactive() {
        return this.isactive;
    }

    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

}


