package com.scrape.BO;
// Generated Sep 3, 2015 2:54:40 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,schema="dbo"
)
public class Users{


     private long id;
     private String fullname;
     private String username;
     private String password;
     private String passwordHint;
     private String email;
     private String systemPasswordEnable;
     private String isactive;
     private Date createDate;
     private Date lastUpdate;

    public Users() {
    }

	
    public Users(long id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }
    public Users(long id, String fullname, String username, String password, String passwordHint, String email, String systemPasswordEnable, String isactive, Date createDate, Date lastUpdate) {
       this.id = id;
       this.fullname = fullname;
       this.username = username;
       this.password = password;
       this.passwordHint = passwordHint;
       this.email = email;
       this.systemPasswordEnable = systemPasswordEnable;
       this.isactive = isactive;
       this.createDate = createDate;
       this.lastUpdate = lastUpdate;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="FULLNAME", length=50)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    
    @Column(name="USERNAME", nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="PASSWORD", nullable=false, length=500)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="PASSWORD_HINT", length=250)
    public String getPasswordHint() {
        return this.passwordHint;
    }
    
    public void setPasswordHint(String passwordHint) {
        this.passwordHint = passwordHint;
    }
    
    @Column(name="EMAIL", length=250)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="SYSTEM_PASSWORD_ENABLE", length=1)
    public String getSystemPasswordEnable() {
        return this.systemPasswordEnable;
    }
    
    public void setSystemPasswordEnable(String systemPasswordEnable) {
        this.systemPasswordEnable = systemPasswordEnable;
    }
    
    @Column(name="ISACTIVE", length=1)
    public String getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }
    
    
    @Column(name="CREATE_DATE", length=10)
    @Temporal(TemporalType.DATE)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    @Column(name="LAST_UPDATE", length=10)
    @Temporal(TemporalType.DATE)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}


