package com.scrape.BO;
// Generated Aug 28, 2015 1:41:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WebData generated by hbm2java
 */
@Entity
@Table(name="WEB_DATA"
    ,schema="dbo"
)
public class WebData{


     private long id;
     private String type;
     private String web;
     private String brand;
     private String link;
     private Date createDate;
     private Date lastUpdate;
     private Character isactive;

    public WebData() {
    }

	
    public WebData(long id) {
        this.id = id;
    }
    public WebData(long id, String type, String web, String brand, String link, Date createDate, Date lastUpdate, Character isactive) {
       this.id = id;
       this.type = type;
       this.web = web;
       this.brand = brand;
       this.link = link;
       this.createDate = createDate;
       this.lastUpdate = lastUpdate;
       this.isactive = isactive;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false, precision=18, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="TYPE", length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="WEB", length=50)
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    
    @Column(name="BRAND", length=50)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    
    @Column(name="LINK", length=250)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    
    @Column(name="CREATE_DATE", length=10)
    @Temporal(TemporalType.DATE)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    @Column(name="LAST_UPDATE", length=10)
    @Temporal(TemporalType.DATE)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    
    @Column(name="ISACTIVE", length=1)
    public Character getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }




}


